version: "3"
services:

  shared_postgres:
    container_name: shared_postgres
    image: postgres:11-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "postgres"
    restart: "always"
    volumes:
      - ./data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "${CITUS_LOGS_SIZE:-100m}"
        max-file: "4"

  shared_redis:
    container_name: shared_redis
    image: redis:4.0.11-alpine
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - '6380:6379'
    volumes:
      - ./data:/var/lib/redis/data
